name: Sample Workflow

on:
  workflow_dispatch:
    inputs:
      status:
        description: 'workflow exit status'
        required: true
        default: true
        type: choice
        options:
          - true
          - false
      time:
        description: 'time to wait'     
        required: true
        default: '30'
        type: choice
        options:
        - 10
        - 30
        - 60
        - 120

jobs:
  wait:
    runs-on: ubuntu-latest
    steps:
      - name: sleep and exit
        run: | 
          sleep ${{ github.event.inputs.time }}s
          [ "${{ github.event.inputs.status }}" = "true" ] && exit 1

