name: Sample Workflow

on:
  workflow_dispatch:
    inputs:
      status:
        description: 'This workflow should fail?'
        required: true
        default: true
        type: choice
        options:
          - true
          - false
      time:
        description: 'How long to wait (seconds)?'     
        required: true
        default: '30'
        type: choice
        options:
        - 10
        - 30
        - 60
        - 120
        - 300

jobs:
  wait:
    runs-on: ubuntu-latest
    steps:
      - name: sleep and exit
        run: | 
          sleep ${{ github.event.inputs.time }}s
          if [[ "${{ github.event.inputs.status }}" == "true" ]]; then exit 1; fi

